baseURL =                   "https://ianteda.com/"
languageCode =              "en-us"
title =                     "Ian Teda"
theme =                     "hugo_theme_materialize"
canonifyURLs =              false
uglyurls =                  true

# Build to temp folder during development
publishDir =                ".build"

googleAnalytics =           "UA-71253711-1"

[taxonomies]
  category =                "categories"
  series =                  "series"

[permalinks]
    blog =                  "blog"

[params]
    author =                "Ian Teda"
    tagLine =               "Husband, father, engineer & explorer."
    email =                 "ian@teda.id.au"
    indexHeader =           "cover-bw-highrise"
    now =                   "now.html"
    facebook =              "https://www.facebook.com/ian.teda"
    github =                "https://github.com/IanTeda"
    twitter =               "https://twitter.com/IanTeda"
    linkedin =              "https://www.linkedin.com/in/ianteda/"
    instagram =             "https://www.instagram.com/ianteda/"
    vimeo =                 "https://vimeo.com/ianteda"
    gplus =                 "https://plus.google.com/+IanTeda"
    youtube =               "https://www.youtube.com/user/IanTeda/"

[[menu.categories]]
    name =                  "Creativity"
    url =                   "creativity"
[[menu.categories]]
    name =                  "Engineering"
    url =                   "engineering"
[[menu.categories]]
    name =                  "Leadership"
    url =                   "leadership"
[[menu.categories]]
    name =                  "Programming"
    url =                   "programming"


[related]

    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold =             80

    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer =          true

    # Will lower case keywords in both queries and in the indexes.
    toLower =               true

    [[related.indices]]
        name =              "keywords"
        weight =            150

    [[related.indices]]
        name  =             "author"
        toLower =           true
        weight =            30

    [[related.indices]]
        name  =             "tags"
        weight =            100

    [[related.indices]]
        name  =             "date"
        weight =            10
        pattern =           "2006"
