baseURL =                   "https://ianteda.com/"
languageCode =              "en-us"
title =                     "Ian Teda"
theme =                     "hugo_theme_materialize"
canonifyURLs =              false
uglyurls =                  false
summaryLength =             45

# Build to temp folder during development
publishDir =                ".build"

[taxonomies]
  category =                "categories"
  series =                  "series"

[permalinks]


[params]
    googleAnalytics =       "UA-71253711-1"
    author =                "Ian Teda"
    tagLine =               "Husband, father, engineer & explorer."
    description =           "I choose to be authentic through honesty, integrity and transparency. With a spirit for creativity, imagination and adventure. Seeking personal growth by being curious, learning and reflecting. Looking for freedom through the discipline of habit. But most of all I am trying to be useful by adding value in what I do."
    email =                 "mailto://ian@teda.id.au"
    indexHeader =           "cover-bw-highrise"
    now =                   "/now"
    facebook =              "https://www.facebook.com/ian.teda"
    github =                "https://github.com/IanTeda"
    twitter =               "https://twitter.com/IanTeda"
    linkedin =              "https://www.linkedin.com/in/ianteda/"
    instagram =             "https://www.instagram.com/ianteda/"
    vimeo =                 "https://vimeo.com/ianteda"
    gplus =                 "https://plus.google.com/+IanTeda"
    youtube =               "https://www.youtube.com/user/IanTeda/"

[[menu.categories]]
    name =                  "Creativity"
    url =                   "/categories/creativity"
[[menu.categories]]
    name =                  "Engineering"
    url =                   "/categories/engineering"
[[menu.categories]]
    name =                  "Leadership"
    url =                   "/categories/leadership"
[[menu.categories]]
    name =                  "Programming"
    url =                   "/categories/programming"

[[menu.series]]
    name =                  "The Engineering Rule Book"
    url =                   "/series/the-engineering-rule-book"
[[menu.series]]
    name =                  "Letters to my Children"
    url =                   "/series/letters-to-my-children"
[[menu.series]]
    name =                  "The Strength Initiative"
    url =                   "/series/the-strength-initiative/"


[related]

    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 0

    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer = true

    # Will lower case keywords in both queries and in the indexes.
    toLower = true

    [[related.indices]]
        name =              "keywords"
        weight =            150

    [[related.indices]]
        name  =             "author"
        toLower =           true
        weight =            30

[[related.indices]]
        name  =             "tags"
        toLower =           true
        weight =            60

    [[related.indices]]
        name  =             "categories"
        weight =            100

    [[related.indices]]
        name  =             "date"
        weight =            10
        pattern =           "2006"